export const UTILS_SET_PROVIDER = "UTILS_SET_PROVIDER";
export const UTILS_SET_ACCOUNTS = "UTILS_SET_ACCOUNTS";
export const UTILS_SET_IS_LOADED = "UTILS_SET_IS_LOADED";
export const UTILS_SET_SELECTED_ACCOUNT = "UTILS_SET_SELECTED_ACCOUNT";
export const UTILS_SET_POLKADT_EXTENSION = "UTILS_SET_POLKADT_EXTENSION";