export const UTILS_SET_ACCOUNTS = 'UTILS_SET_ACCOUNTS';
export const UTILS_SET_IS_LOADED = 'UTILS_SET_IS_LOADED';
export const UTILS_SET_SELECTED_ACCOUNT = 'UTILS_SET_SELECTED_ACCOUNT';
export const UTILS_SET_POLKADT_EXTENSION = 'UTILS_SET_POLKADT_EXTENSION';

export const TOKENS_SET_ALL = 'TOKENS_SET_ALL';
export const TOKENS_ADD_TOKEN = 'TOKENS_ADD_TOKEN';
export const TOKENS_UPDATE_TOKEN_BALANCE = 'TOKENS_UPDATE_TOKEN_BALANCE';
